djangodemo/accounts/urls.py
from django.urls import path, include
from . import views

# 命名空间，让django能够将这些URL与其他应用程序的URL区分开
app_name='accounts'
urlpatterns = [
    # 包含django定义的默认身份验证URL
    # 默认的URL有 login logout
    path('', include('django.contrib.auth.urls')),
    # 注册页面
    path('register/', views.register, name='register'),
]

djangodemo/learning_logs/urls.py
'''定义learning_logs的URL pattern'''
from django.urls import path
from . import views

# 定义app_name,让django能够将此urls.py文件与其他应用程序中的urls.py文件区分开
app_name='learning_logs'
urlpatterns = [
    # 主页 path函数的一个入参是url，第二个入参指定调用views.py中的哪个函数；第三个参数是这个url别名，方便引用
    path('index', views.index, name='index'),
    # 显示所有topic的页面
    path('topics', views.topics, name='topics'),
    path('about', views.about, name='about'),
    # 特定Topic下d所有entry查询页面
    path('topics/<int:topic_id>', views.topic, name='topic'),
    # 用于添加新主题的网页
    path('new_topic', views.new_topic, name='new_topic'),
    path('new_entry/<int:topic_id>', views.new_entry, name='new_entry'),
    path('edit_entry/<int:entry_id>', views.edit_entry, name='edit_entry'),
]

djangodemo/ll_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404
from django.conf.urls import handler500
from learning_logs import views

# handler404要放在ll_project目录下才能生效，learning_logs里不可以
handler404 = views.custom_404_view
handler500 = views.custom_500_view

# 默认的urls.py位于 ll_project 文件夹中
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('learning_logs.urls')),
    # 匹配所有以accounts开头的URL
    path('accounts/',include('accounts.urls')),
]

djangodemo/accounts/models.py
from django.db import models

# Create your models here.

djangodemo/learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

# 用户将存储的主题
class Topic(models.Model):
    """用户学习的主题"""
    # CharField 由字符组成的数据
    text = models.CharField(max_length=200)
    # 用户创建新主题时，django自动设置为当前的日期和时间
    date_added = models.DateTimeField(auto_now_add=True)
    # 该主题的创建人
    owner = models.ForeignKey(User, on_delete=models.CASCADE,
                              default=1  # 默认关联 User.id = 1
                              )

    def __str__(self):
        return self.text + ';'

class Entry(models.Model):
    """学到的有关某个主题的具体知识"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """返回一个表示条目的简单字符串"""
        return f"{self.text[:50]}。。。"

djangodemo/learning_logs/forms.py
# 学习django的表单处理
from django import forms
from .models import Topic,Entry

'''
下面这段代码翻译成java
public class TopicForm extends ModelForm {
    // 使用内部静态类保存配置
    public static class Meta {
        public Class<?> model = Topic.class;
        public String[] fields = {"text"};
    }
}
让类本身携带额外的元信息（metadata），但又不影响实例的行为。
这类似于 Java 中使用注解（annotations）或 XML 配置文件来描述类行为的方式，只不过 Python 更倾向于用类结构本身来表达这些配置。
'''
class TopicForm(forms.ModelForm):
    # 定义嵌套内部类，存放django表单信息
    # 在 Django 中，class Meta 是一种约定俗成的写法，用于为类提供额外的配置信息，类似于 Java 中的配置类或注解，但更加简洁和灵活。
    class Meta:
        # 在 Python 中，类本身就是一种值（first-class object），可以像变量一样传递。所以这里不是model=Topic()
        # 类似java的 model=Topic.class
        model= Topic
        # Topic model中有 text\date_added 两个字段，这里声明只涉及text
        fields = ['text']
        # label会作为表单label展示
        labels = {'text':'主题名称: '}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        # 给字段指定空白标签
        labels = {'text':'请输入文本-label'}
        # 在python代码里控制html显示的表单元素，比较便捷
        widgets = {'text': forms.Textarea(attrs={'cols':80})}

djangodemo/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    '''注册新用户'''
    if request.method != 'POST':
        # 显示空白的注册表单
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            # 将用户名和密码的hash值保存到库中
            new_user = form.save()
            # 为用户创建有效会话，自动登录
            login(request, new_user)
            # 重定向到主页
            return redirect('learning_logs:index')
    # 显示空表单或指出表单无效
    context = {'form':form}
    return render(request, 'registration/register.html', context)

djangodemo/learning_logs/views.py
from django.shortcuts import render, redirect
from .models import Topic, Entry
from .forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required
from django.http import Http404
# 不是import Http500，实际上，跳到404页面，import Http404不是必须的，仅仅是因为主动raise了
from django.http import HttpResponseServerError

# 通用
def custom_404_view(request, exception=None):
    return render(request, 'learning_logs/404.html', status=404)
# status必须是一个int
def custom_500_view(request, exception=None):
    return render(request, 'learning_logs/500.html', status=500)

# Create your views here.
def index(request):
    '''学习笔记的主页'''
    return render(request,'learning_logs/index.html')

@login_required #添加登录检查装饰器，需要在settings.py中设置重定向的页面
def topics(request):
    '''显示所有主题 按创建人筛选'''
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

def about(request):
    context={}
    return render(request, 'learning_logs/about.html', context)

@login_required
def topic(request, topic_id):
    """显示单个主题及其所有条目"""
    topic = Topic.objects.get(id=topic_id)
    '''确认该topic属于当前用户'''
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic':topic, 'entries':entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    '''添加新主题'''
    if request.method != 'POST':
        # 未提交数据：创建一个表单
        form = TopicForm()
    else:
        form = TopicForm(data=request.POST) #对象form包含用户提交的信息
        # 校验表单字段不可为空，类型正确。Topic model text字段限制了长度，这里也会校验
        if form.is_valid():
            # 关联请求中的user再保存
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            # form.save() #save会将表单数据写入数据库
            # 用户提交数据后重定向到topics网页，redirect函数将视图 learning_logs:topics作为参数，将用户重定向到与该视图相关联的网页
            return redirect('learning_logs:topics')
    # 显示空表单或指出表单数据无效
    context = {'form':form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    '''在特定主题中添加新条目'''
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry=form.save(commit=False)
            new_entry.topic=topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)

    context = {'topic':topic,'form':form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        # 这里专门抛出500，以显示与404的不同
        raise HttpResponseServerError

    if request.method != 'POST':
        # 通过instance指定库里查出来的原始数据对象，通过data设置表单传入的新值
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)
    context = {'entry':entry, 'topic':topic, 'form':form}
    return render(request, 'learning_logs/edit_entry.html', context)

djangodemo/learning_logs/templates/learning_logs/about.html
{% extends 'learning_logs/base_bs.html' %}

{%block content%}
    <p1>Learning Logs</p1>
    <p>一个学习笔记网站，django demo</p>
    <p>Author: H.D.F</p>
{%endblock content%}

djangodemo/learning_logs/templates/learning_logs/base.html
<p>
    <!-- 表示跳转到 learning_logs/urls.py中定义的名为index的URL -->
     <!-- learning_logs是一个命名空间，这个命名空间来自文件 learning_logs/urls.py中定义的app_name -->
    <a href="{% url 'learning_logs:index' %}">Learning Log</a> -
    <a href="{% url 'learning_logs:topics' %}">Topics</a> - 
    <!-- django中的身份验证系统中定义了user及其属性 -->
    {% if user.is_authenticated %}
        Hello, {{user.username}}.
        <div style="position: absolute;top: 5px;left: 280px;">
            <!-- 为防止恶意注销他人账户，要采用表单方式注销，并提交模板标签csrf_token防止跨站恶意请求 -->
            <form action="{% url 'accounts:logout' %}" method="post">
                <!-- 这一行会被渲染成 <input type="hidden" name="csrfmiddleware.csrf_token" value="ABCDEF1234567890XYZ">  -->
                {% csrf_token %}
                <button name="submit">Log out</button>
            </form>
        </div>
    {% else %}
        <a href="{% url 'accounts:register' %}">Register</a> | 
        <a href="{% url 'accounts:login' %}">Log in</a>
    {% endif %}
</p>
{% block content %}
<span>
    这是模板文件通用内容
</span>
{% endblock content %}

djangodemo/learning_logs/templates/learning_logs/base_bs.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <title>学习笔记</title>

        {% load django_bootstrap5 %}
        <!-- django-bootstrap5中的定制模板标签，加载实现Bootstrap样式所需的所有CSS文件 -->
        {% bootstrap_css %}
        <!-- 启用可能在页面中使用的所有交互行为，如可折叠的导航栏 -->
        {% bootstrap_javascript %}

    </head>
    <body>
        <!-- mb-4 表示 margin-bottom,确保导航栏和页面其他部分之间有一些空白区域 -->
        <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log</a>
                <!-- 窗口太窄时展示下拉列表，隐藏了水平导航栏 -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarCollapse" aria-controls="navbarCollapse"
                aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <!-- 定义导航栏的可折叠部分 -->
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0 ">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'learning_logs:topics' %}">Topics</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{%url 'learning_logs:about'%}">About</a>
                        </li>
                    </ul> <!---定义导航栏左侧链接d代码-->

                    <!-- 与账户相关d链接 -->
                     <!-- ms-auto margin-start-automatic 自动左边距，确保这组链接位于窗口右侧 -->
                    <ul class="navbar-nav ms-auto mb-2 mb-md-0">
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <!-- 注意区分 \{\%\%\} \{\{\}\} 两种标签-->
                            <span class="navbar-text me-2">Hello, {{user.username}}</span>
                        </li>
                        {%else%}
                        <li class="nav-item">
                            <a class="nav-link" href="{%url 'accounts:register'%}">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{%url 'accounts:login'%}">Log in</a>
                        </li>
                        {% endif %}
                    </ul><!--与账户相关的链接-->
                    {% if user.is_authenticated%}
                    <form action="{% url 'accounts:logout'%} ", method="post">
                        {%csrf_token%}
                        <button name="submit" class="btn btn-outline-secondary btn-sm">Log out</button>
                    </form>
                    {%endif%}
                </div> <!--定义导航栏可折叠部分d代码-->
            </div> <!--定义导航栏容器的代码-->
        </nav> <!--定义导航栏的代码-->

        <!-- 借助bootstrap选择器container对页面元素进行分组 -->
        <main class="container">
            <!-- 选择器border-bottom将在page_header块下添加较细的边框 -->
            <div class="pb-2 mb-2 border-bottom">
                {% block page_header %}{% endblock page_header%}
            </div>
            <div><!--各个页面的block content中的内容会被防止到这个标记区域内-->
                {%block content%}{%endblock content%}
            </div>
        </main>

    </body>
</html>

djangodemo/learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base_bs.html' %}
{% load django_bootstrap5 %}

{% block page_header%}
<h2>Edit this entry</h2>
<p>
    当前主题：<a href="{% url 'learning_logs:topic' topic.id %}"></a>
</p>
{% endblock page_header%}

{% block content %}
    <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
        {% csrf_token %}
        {%bootstrap_form form%}
        {%bootstrap_button button_type="submit" content="Save changes"%}

        <!-- {{form.as_div}} -->
        <!-- <button name="submit">Save changes</button> -->
    </form>
{% endblock content %}

djangodemo/learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base_bs.html' %}
{%block page_header%}
<div class="p-3 mb-4 bg-light border rounded-3">
    <div class="container-fluid py-4">
        <h1 class="display-3">Track your learning.</h1>
        <p class="lead">Make your own learning Log, and keep a list of the topics you're learning about. Whenever you learn something new about a topic, make an entry summarizing what you've learned.</p>
        {%if user.is_authenticated%}
        <a class="btn btn-success btn-lg mt-1" href="{%url 'learning_logs:topics'%}">好好学习，天天向上></a>
        {%else%}
        <a class="btn btn-primary btn-lg mt-1" href="{%url 'accounts:register'%}">Go & Register Accounts >></a>
        {%endif%}
    </div>
</div>
{% endblock page_header%}

djangodemo/learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base_bs.html' %}
{% load django_bootstrap5 %}

{% block page_header%}
<h2>Create new Entry</h2>
<p>
    当前主题：
    <!-- 双大括号 会调用对象的__str__方法 -->
    <a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a>
</p>
{% endblock page_header%}

{% block content %}
    <form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
        {%csrf_token%}
        {%bootstrap_form form%}
        {%bootstrap_button button_type="submit" content="Add Entry"%}

        <!-- 在views.py中设置过context中的form对象，这里就可以直接使用了 -->
        <!-- {{form.as_div}} -->
        <!-- <button name="'submit">Add Entry</button> -->
    </form>
{% endblock content %}

djangodemo/learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base_bs.html' %}
{% block content %}
    <p>Add a new topic:</p>
    <!-- action 告知提交数据到 learning_logs/urls.py 中定义的new_topic上 -->
    <form action="{% url 'learning_logs:new_topic' %}" method="POST">
        <!-- 使用模板标签防止攻击者利用表单对服务器进行未经授权的访问——跨站请求伪造 -->
        {% csrf_token %}
        <!-- 让 django 自动创建显示表单所需的全部字段，修饰符as_div表示让django将所有表单元素渲染为div元素，更整洁 -->
        {{ form.as_div }}
        <button name="submit">Add topic</button>
    </form>
{% endblock content %}

djangodemo/learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base_bs.html' %}

{% block page_header%}
<!-- views层已经查询出topic放到context里了，所以这里可以直接使用这个变量 -->
<h1>{{topic.text}}</h1>
{% endblock page_header%}

{% block content %}
    <!-- <p>Topic: {{topic.text}}</p> -->
    <p>
        <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
    </p>
    {%for entry in entries%}
        <div class="card mb-3">
            <!-- 包含时间戳和编辑链接的标题 -->
            <h4 class="card-header">
                {{entry.date_added|date:'Y-M-d H:i'}}
                <small>
                    <a href="{%url 'learning_logs:edit_entry' entry.id%}">edit Entry</a>
                </small>
            </h4>
            <div class="card-body">{{entry.text|linebreaks}}</div>
        </div>
    {%empty%}
        <p>There are no entries for this topic yet.</p>
    {%endfor%}

{% endblock content %}

djangodemo/learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base_bs.html' %}
{%block page_header%}
<h1>Topics</h1>
{%endblock page_header%}

{% block content %}
<ul class="list-group border-bottom pb-2 mb-4">
    {% for topic in topics %}
        <li class="list-group-item border-0">
            <!-- 使用模板标签url根据learning_logs中名为topic的URL pattern生成合适的链接 -->
            <a href="{% url 'learning_logs:topic' topic.id %}">{{topic.text}}</a>
        </li>
    {% empty %}
        <li class="list-group-item border-0">No topics have been added yet.</li>
    {% endfor %}
</ul><!-- 初始跳转链接和提交表单链接都是 new_topic，所以views中的new_topic方法接收的入参可能为空 -->
<a href="{% url 'learning_logs:new_topic' %}" class="btn btn-warning">Create new topic</a>
{% endblock content%}